config/routes.rb
Rails.application.routes.draw do

  #Static pages
  root 'static_pages#home'
  get 'error404' => 'static_pages#error404'
  get 'conditions' => 'static_pages#conditions'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  #Non-statical pages
  resources :excursions do
    resources :registrations
    get 'download', on: :member, constraints: { format: /(html|csv)/ }
  end
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :reset_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { minimum: 2 , maximum: 50}, format: { with: /\A[A-Za-z\séèóòàáíúñç\']+\z/, message: I18n.t('models.errors.invalid_characters') }
  validates :surname, presence: true, length: { minimum: 2, maximum: 100 }, format: { with: /\A[A-Za-z\séèóòàáíúñç\']+\z/, message: I18n.t('models.errors.invalid_characters') }
  validates :phoneNumber, presence: true, length: { is: 9 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:true, format: { with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def send_registration_confirmation(excursion, registration)
    UserMailer.registration_confirmation(self, excursion, registration).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: [:index, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    set_default_active_and_role(@user)
    if @user.save
      log_in @user
      flash[:success] = I18n.t('success.signup_correct')
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = I18n.t('success.updated_info')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.update_attributes(change_active_attribute)
      flash[:success] = I18n.t('success.user_deactivated')
      redirect_to users_path
    else
      flash.now[:danger] = I18n.t('error.unable_to_deactivate')
      redirect_to @user
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :surname, :phoneNumber, :email, :password,
    :password_confirmation)
  end

  #Confirms that user is logged in
  def logged_in_user
    unless logged_in?
      flash[:danger] = I18n.t('errors.login_first')
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless (current_user?(@user) || admin_user?)
  end

  # Confirms the user has admin privileges.
  def admin_user
    unless admin_user?
      flash[:danger] = I18n.t('errors.unprivileged_user')
      redirect_to root_url
    end
  end

  #Set default properties (active user and not admin)
  def set_default_active_and_role(user)
    user.admin = false
    user.active = true
  end

  #Deactive an user
  def change_active_attribute
    user_hash = Hash.new()
    @user.attributes.each do |key, value|
      user_hash[key] = value
    end
    user_hash["active"] = !user_hash["active"]
    user_hash
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, t('views.users.update_user_info')) %>
<div class="page-header">
  <h4><%= t('views.users.update_user_info') %></h4>
</div>
<div class="container">
  <%= render 'users/error_messages' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      <p>
        <%= f.label t('views.users.name') %>
        <%= f.text_field :name, class: 'form-control' %>
      </p>
      <p>
        <%= f.label t('views.users.surname') %>
        <%= f.text_field :surname, class: 'form-control' %>
      </p>
      <p>
        <%= f.label t('views.users.phone') %>
        <%= f.number_field :phoneNumber, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :password, t('views.users.password') %>
        <%= f.password_field :password, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :password_confirmation, t('views.users.confirm_password') %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </p>
      <p>
        <%= f.submit t('views.users.update'), class: "btn custom-btn" %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<div class="page-header">
  <h4><%= t('views.users.user_list') %></h4>
</div>
<div class="container-fluid">
  <table class="table">
    <tr>
      <th><%= t('views.users.name') %></th>
      <th><%= t('views.users.surname') %></th>
      <th><%= t('views.users.phone') %></th>
      <th><%= t('views.users.email') %></th>
      <th><%= t('views.users.active') %></th>
      <th><%= t('views.users.administrator') %></th>
      <th><%= t('views.users.registration_date') %></th>
      <th><%= t('views.users.edit') %></th>
      <th><%= t('views.users.change_state') %></th>
    </tr>

    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.surname %></td>
      <td><%= user.phoneNumber %></td>
      <td><%= user.email %></td>
      <td><%= user.active? ? t('views.users.yes') : t('views.users.no') %></td>
      <td><%= user.admin? ? t('views.users.yes') : t('views.users.no') %></td>
      <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
      <td><%= link_to  edit_user_path(user) do %>
        <span class="glyphicon glyphicon-edit"></span>
        <% end %></td>
      <% @label = user.active? ? t('views.users.deactivate') : t('views.users.activate') %>
      <td><%= link_to @label, user_path(user),
      method: :delete,
      data: { confirm: t('views.users.are_you_sure') }, class: "btn custom-btn" %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, t('views.users.signup')) %>
<div class="page-header">
  <h4><%= t('views.users.signup') %></h4>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/error_messages' %>

    <%= form_for(@user) do |f| %>

    <p>
      <%= f.label t('views.users.name') %>
      <%= f.text_field :name, class: 'form-control' %>
    </p>
    <p>
      <%= f.label t('views.users.surname') %>
      <%= f.text_field :surname, class: 'form-control' %>
    </p>
    <p>
      <%= f.label t('views.users.phone') %>
      <%= f.number_field :phoneNumber, class: 'form-control' %>
    </p>
    <p>
      <%= f.label t('views.users.email') %>
      <%= f.email_field :email, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password, t('views.users.password') %>
      <%= f.password_field :password, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation, t('views.users.confirm_password') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit t('views.users.signup'), class: "btn custom-btn" %>
    </p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, t('views.users.user_info')) %>
<div class="page-header">
  <h4><%= t('views.users.details_of').concat(@user.name).concat(" ").concat(@user.surname)%></h4>
</div>
<div class="container-fluid">
  <dl class="dl-horizontal">
    <dt><%= t('views.users.name') %></dt>
    <dd><%= @user.name %></dd>
    <dt><%= t('views.users.surname') %></dt>
    <dd><%= @user.surname %></dd>
    <dt><%= t('views.users.phone') %></dt>
    <dd><%= @user.phoneNumber %></dd>
    <dt><%= t('views.users.email') %></dt>
    <dd><%= @user.email %></dd>
  </dl>
  <%= link_to t('views.users.back'), root_url, class: "btn custom-btn" %>
</div>