config/routes.rb
Rails.application.routes.draw do

  #Static pages
  root 'static_pages#home'
  get 'error404' => 'static_pages#error404'
  get 'conditions' => 'static_pages#conditions'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  #Non-statical pages
  resources :excursions do
    resources :registrations
    get 'download', on: :member, constraints: { format: /(html|csv)/ }
  end
  resources :users
end

app/models/excursion.rb
require 'csv'

class Excursion < ActiveRecord::Base
  has_many :registrations

  validates :name, presence: true, length: { minimum: 4, maximum: 50 }, format: { with: /\A[A-Za-z\séèóòàáíúñç\']+\z/, message: I18n.t('models.errors.invalid_characters') }
  validates :busSpots, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0}
  validates :lunchSpots, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0}

  def to_csv(options = {})
    attributes = %w{name phoneNumber email busSpots lunchSpots}
    CSV.generate(options) do |csv|
      registration_column_names = attributes

      csv << registration_column_names

      self.registrations.each do |registration|
        csv << registration.attributes.values_at(*registration_column_names)
      end
    end
  end

end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @excursions = Excursion.all
  end

  def show
    @excursion = Excursion.find(params[:id])
  end

  def new
    @excursion = Excursion.new
  end

  def edit
    @excursion = Excursion.find(params[:id])
  end

  def create
    @excursion = Excursion.new(excursion_params)

    if @excursion.save
      redirect_to @excursion
    else
      render 'new'
    end
  end

  def update
    @excursion = Excursion.find(params[:id])
    if @excursion.update(excursion_params)
      redirect_to @excursion
    else
      render 'edit'
    end
  end

  def destroy
    @excursion = Excursion.find(params[:id])
    @excursion.destroy

    redirect_to excursions_path
  end

  def download
    @excursion = Excursion.find(params[:id])
    respond_to do |format|
      format.html
      format.csv { send_data @excursion.to_csv , filename: "registrations-#{@excursion.name}.csv"}
    end
  end


  private
  def excursion_params
    params.require(:excursion).permit(:name, :busSpots, :lunchSpots, :active)
  end

  # Confirms the user has admin privileges.
  def admin_user
    unless admin_user?
      flash[:danger] = I18n.t('errors.unprivileged_user')
      redirect_to root_url
    end
  end

  #Confirms that user is logged in
  def logged_in_user
    unless logged_in?
      flash[:danger] = I18n.t('errors.login_first')
      redirect_to login_url
    end
  end
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/views/excursions/_error_messages.html.erb
<% if @excursion.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@excursion.errors.count, "error") %> prohibited
        this excursion from being saved:
    </h2>
    <ul>
        <% @excursion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/excursions/_form.html.erb
<div class="container">
  <%= render 'excursions/error_messages' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @excursion do |f| %>
      <p>
        <%= f.label t('views.excursions.name') %>
        <%= f.text_field :name, class: "form-control" %>
      </p>
      <p>
        <%= f.label t('views.excursions.bus_spots') %>
        <%= f.number_field :busSpots, class: "form-control" %>
      </p>
      <p>
        <%= f.label t('views.excursions.lunch_spots') %>
        <%= f.number_field :lunchSpots, class: "form-control" %>
      </p>
      <p>
        <%= f.label t('views.excursions.active') %>
        <%= f.check_box :active %>
      </p>
      <p>
      <% if  @excursion.id != nil %>
         <%= f.submit t('views.excursions.update'), class: "btn custom-btn"%>
      <% else %>
	       <%= f.submit t('views.excursions.create'), class: "btn custom-btn"%>
      <% end %>
      </p>
    <% end %>
    </div>
  </div>
  <%= link_to t('views.excursions.back'), excursions_path, class: 'btn custom-btn' %>
</div>

app/views/excursions/edit.html.erb
<h3><%= t('views.excursions.edit_excursion') %></h3>

<%= render 'form' %>

app/views/excursions/index.html.erb
<% provide(:title, "Excursions") %>
<div class="page-header">
  <h4><%= t('views.excursions.list') %></h4>
</div>
<div class="container-fluid">
  <%= link_to new_excursion_path, class: "btn custom-btn" do %>
  <span class="glyphicon glyphicon-plus"></span> <%= t('views.excursions.new') %>
  <% end %></br></br>
  <table class="table">
    <tr>
      <th><%= t('views.excursions.name') %></th>
      <th><%= t('views.excursions.bus_spots') %></th>
      <th><%= t('views.excursions.lunch_spots') %></th>
      <th><%= t('views.excursions.active') %></th>
      <th><%= t('views.excursions.registrations') %></th>
      <th><%= t('views.excursions.show') %></th>
      <th><%= t('views.excursions.edit') %></th>
      <th><%= t('views.excursions.export') %><th>
      <th><%= t('views.excursions.delete') %></th>
    </tr>

    <% @excursions.each do |excursion| %>
    <tr>
      <td><%= excursion.name %></td>
      <td><%= excursion.busSpots %></td>
      <td><%= excursion.lunchSpots %></td>
      <td><%= excursion.active? ? t('views.excursions.yes') : t('views.excursions.no') %></td>
      <td><%= link_to excursion_registrations_path(excursion) do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        <% end %>
      </td>
      <td><%= link_to excursion_path(excursion) do %>
        <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </td>
      <td><%= link_to edit_excursion_path(excursion) do %>
        <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      </td>
      <td><%= link_to download_excursion_path(:id => excursion.id, :format => :csv) do %>
        <span class="glyphicon glyphicon-save"></span>
        <% end %>
      </td>
      <td>
        <%= link_to excursion_path(excursion),
        method: :delete,
        data: { confirm: t('views.excursions.are_you_sure') } do %>
        <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  <%= link_to t('views.excursions.back'), root_path, class: "btn custom-btn" %>
</div>

app/views/excursions/new.html.erb
<% provide(:title, "Create excursion") %>
<div class="page-header">
  <h4><%= t('views.excursions.create_excursion') %></h4>
</div>
<%= render 'form' %>

app/views/excursions/show.html.erb
<% provide(:title, "Excursions") %>
<div class="page-header">
  <h4><%= t('views.excursions.excursion_info') %></h4>
</div>
<div class="container-fluid">
  <dl class="dl-horizontal">
    <dt><%= t('views.excursions.name') %></dt>
    <dd><%= @excursion.name %></dd>
    <dt><%= t('views.excursions.bus_spots') %></dt>
    <dd><%= @excursion.busSpots %></dd>
    <dt><%= t('views.excursions.lunch_spots') %></dt>
    <dd><%= @excursion.lunchSpots %></dd>
    <dt><%= t('views.excursions.active') %>?</dt>
    <dd><%= @excursion.active ? t('views.excursions.yes') : t('views.excursions.no') %></dd>
  </dl>
  <%= link_to t('views.excursions.back'), excursions_path, class: 'btn custom-btn' %>
</div>