config/routes.rb
Rails.application.routes.draw do

  #Static pages
  root 'static_pages#home'
  get 'error404' => 'static_pages#error404'
  get 'conditions' => 'static_pages#conditions'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  #Non-statical pages
  resources :excursions do
    resources :registrations
    get 'download', on: :member, constraints: { format: /(html|csv)/ }
  end
  resources :users
end

app/views/layouts/_admin_home.html.erb
<p>
  <%= t('views.layouts.enter_excursions') %></br>
  <%= link_to excursions_path, class: "btn custom-btn" do%>
    <span class=" glyphicon glyphicon-tree-conifer "></span> <%= t('views.layouts.excursions') %>
  <% end %>
</p>
<p>
  <%= t('views.layouts.enter_users') %></br>
  <%= link_to users_path, class: "btn custom-btn" do%>
    <span class=" glyphicon glyphicon-user "></span> <%= t('views.layouts.users') %>
  <% end %>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Excursions app, 2018.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to t('apptitle'), root_path, id: "logo" %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="glyphicon glyphicon-menu-hamburger" style="color:white;border-color:#34302D;background-color:#34302D"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('index.header.home'),   root_path %></li>
          <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('index.header.my_account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('index.header.profile'), current_user %></li>
              <li><%= link_to t('index.header.settings'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t('index.header.logout'), logout_path, method: "delete" %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to t('index.signin'), login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_home_header.html.erb
<% provide(:title, "Inici") %>
<div class="page-header">
  <h4><%= t('views.layouts.welcome_app') %></h4>
</div>

app/views/layouts/_noadmin_home.html.erb
<p>
  <% if Excursion.last != nil %>
    <%= t('views.layouts.registration_last_excursion') %> </br>
    <%= link_to  new_excursion_registration_path(Excursion.last), class: "btn custom-btn" do%>
      <span class=" glyphicon glyphicon-pencil "></span> <%= t('views.layouts.register') %>
    <% end %>
  <% else %>
    <%= t('views.layouts.no_active_excursion') %>
  <% end %>
</p>

app/views/layouts/_nologged_home.html.erb
<p>
  <%= t('views.layouts.no_logged_intro') %>
</p>
<p>
  <%= t('views.layouts.login_intro') %> </br>
  <%= link_to login_path, class: "btn custom-btn center" do%>
  <span class="glyphicon glyphicon-log-in"></span> <%= t('index.signin') %>
  <% end %>
</p>
<p>
  <%= t('views.layouts.signup_intro') %> </br>
  <%= link_to new_user_path, class: "btn custom-btn center" do%>
  <span class="glyphicon glyphicon-pencil"></span> <%= t('index.signup') %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
      	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>

            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>